(CI): use new c7 container for test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,6 @@
 variables:
     # Как долго хранить тестовые сборки, дней
-    DEV_EXPIRE_IN: "7"
+    DEV_EXPIRE_IN: "15"
     # Каталог куда собираются тестовые сборки
     DEV_RPMDIR: "/var/ftp/pvt/Etersoft/RX@Etersoft/CI"
     # каталог с конфигурациями для rxclient
@@ -21,7 +21,13 @@ Release:
     - /usr/bin/rpmlog -q -r -l
     - korinf -f rx-etersoft.spec x86_64/ALTLinux/c7 /var/ftp/pvt/Etersoft/RX@Etersoft/c7
     - git push -f --tags gitlab HEAD:c7
-  
+    - |
+      echo "release (c7):" > last_changes.txt
+      echo "-------------" >> last_changes.txt
+      echo "" >> last_changes.txt
+      rpmlog -q --last-changelog >> last_changes.txt
+      rx_bot_pub_file.py last_changes.txt || echo "ignore event bot error.."
+      
   after_script:
     - mkdir -p RPM/log; cp -rf ${HOME}/RPM/log/*rx-etersoft*.log RPM/log/
     - mkdir -p korinf-log; cp -rf ${HOME}/RPM/tmp/korinf-log/* korinf-log/
@@ -43,10 +49,9 @@ test build:
   script:
     - export TMPDIR=/tmp/.private/${USER}; export TMP=${TMPDIR}
     - export RPMDIR=${DEV_RPMDIR}/$BUILD_ID
-    - eterremove remove --days $DEV_EXPIRE_IN dirs ${DEV_RPMDIR} --notest || echo "ignore remove error.."
+    - eterremove remove --days $DEV_EXPIRE_IN --notest dirs ${DEV_RPMDIR}/ || echo "ignore remove error.."
     - mkdir -p $RPMDIR/sources
-    - /usr/bin/rpmlog -q -r -l
-    - korinf -f rx-etersoft.spec x86_64/ALTLinux/p8 ${RPMDIR}
+    - /usr/bin/rpmlog -q -s -l
     - korinf -f rx-etersoft.spec x86_64/ALTLinux/c7 ${RPMDIR}
   only:
     - /^c7-ci-.*/
@@ -68,7 +73,7 @@ Testing:
       mkdir -p $CI_PROJECT_DIR/.daas/addons/
       cp $DAAS_ADDONS_DIR/rx-test.list $CI_PROJECT_DIR/.daas/addons/
       subst "s|{{BUILD_ID}}|$BUILD_ID|g" $CI_PROJECT_DIR/.daas/addons/rx-test.list
-      subst "s|Sisyphus|p8|g" $CI_PROJECT_DIR/.daas/addons/rx-test.list
+      subst "s|Sisyphus|c7|g" $CI_PROJECT_DIR/.daas/addons/rx-test.list
   script:
     - daas gen
     - cd $DAAS_OUTDIR/rx-etersoft-$BUILD_ID/
@@ -83,11 +88,14 @@ Testing:
       chmod a+rw $HOME/$RXCLIENT_CONFDIR/rx-server-$BUILD_ID.nxs || echo "ignore chmod error.."
     # удаляем старые файлы конфигурации
     - find $HOME/$RXCLIENT_CONFDIR/ -mindepth 1 -mtime +$DEV_EXPIRE_IN -print -delete || echo "ignore delete old configs error"
-    - |
-      echo "                 SERVER IP: $RX_SERVER_IP"
-      echo "           RXCLIENT CONFIG: rx-etersoft-$BUILD_ID"
-      echo "REMOTE CONNECT to RXSERVER: ssh -p $CI_BUILD_ID guest@$(hostname -s)"
-
+    - | 
+      echo "        Packages: ${DEV_RPMDIR}/$BUILD_ID"
+      echo "        RXSERVER: ssh -p $CI_BUILD_ID guest@$(hostname -s)"
+      echo "External info: "
+      echo "        RXCLIENT: ssh -p 7777 guest@$(hostname -s)"
+      echo " RXCLIENT CONFIG: rx-etersoft-$BUILD_ID"
+      echo "       SERVER IP: $RX_SERVER_IP"
+      
   only:
     - /^c7-docker-ci-.*/
 
