(CI): (c7): use rx-daas-templates project

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,9 +3,14 @@ variables:
     DEV_EXPIRE_IN: "7"
     # Каталог куда собираются тестовые сборки
     DEV_RPMDIR: "/var/ftp/pvt/Etersoft/RX@Etersoft/CI"
+    # каталог с конфигурациями для rxclient
+    RXCLIENT_CONFDIR: "docker-rx-client/rxclient-config"
+    BUILD_ID: "$CI_PIPELINE_ID"
 
 stages:
   - build
+  - test
+  - cleanup
 
 build and public:
   stage: build
@@ -36,14 +41,87 @@ test build:
   stage: build
   script:
     - export TMPDIR=/tmp/.private/${USER}; export TMP=${TMPDIR}
-    - export RPMDIR=${DEV_RPMDIR}/$CI_BUILD_ID
+    - export RPMDIR=${DEV_RPMDIR}/$BUILD_ID
+    - eterremove remove --days $DEV_EXPIRE_IN dirs ${DEV_RPMDIR} --notest || echo "ignore remove error.."
     - mkdir -p $RPMDIR/sources
-    - eterremove remove --days $DEV_EXPIRE_IN dirs ${DEV_RPMDIR} || echo "ignore remove error.."
     - /usr/bin/rpmlog -q -r -l
     - korinf -f rx-etersoft.spec x86_64/ALTLinux/p8 ${RPMDIR}
     - korinf -f rx-etersoft.spec x86_64/ALTLinux/c7 ${RPMDIR}
   only:
     - /^c7-ci-.*/
+    - /^c7-docker-ci.*/
 
   tags:
     - rx-build
+
+Testing:
+  stage: test
+  #when: manual
+  before_script:
+    - export DAAS_TEMPLATES_DIR="$HOME/.daas/templates"
+    - export DAAS_ADDONS_DIR="$HOME/.daas/addons"
+    - export DAAS_OUTDIR="$CI_PROJECT_DIR/daas-rx-etersoft"
+    - export DAAS_IMAGE_POSTFIX="-$CI_COMMIT_REF_NAME-build$BUILD_ID"
+    - export "SERVICE_NAME=rx-etersoft-$BUILD_ID"
+    - |
+      mkdir -p $CI_PROJECT_DIR/.daas/addons/
+      cp $DAAS_ADDONS_DIR/rx-test.list $CI_PROJECT_DIR/.daas/addons/
+      subst "s|{{BUILD_ID}}|$BUILD_ID|g" $CI_PROJECT_DIR/.daas/addons/rx-test.list
+      subst "s|Sisyphus|p8|g" $CI_PROJECT_DIR/.daas/addons/rx-test.list
+  script:
+    - daas gen
+    - cd $DAAS_OUTDIR/rx-etersoft-$BUILD_ID/
+    - docker-compose build --force-rm
+    - $HOME/bin/start-rxclient-tester.sh
+    - docker-compose up -d
+    - export RX_SERVER_IP=$(curl -s http://localhost:8500/v1/catalog/service/$SERVICE_NAME | jq '.[].ServiceAddress' | sed 's|"||g')
+    - |
+      mkdir -p $CI_PROJECT_DIR/.daas/templates/
+      cp $DAAS_TEMPLATES_DIR/rx-server.nxs.tpl $CI_PROJECT_DIR/.daas/templates/
+      cat $CI_PROJECT_DIR/.daas/templates/rx-server.nxs.tpl | sed "s|RX_SERVER_IP|${RX_SERVER_IP}|g" > $HOME/$RXCLIENT_CONFDIR/rx-server-$BUILD_ID.nxs
+      chmod a+rw $HOME/$RXCLIENT_CONFDIR/rx-server-$BUILD_ID.nxs || echo "ignore chmod error.."
+    # удаляем старые файлы конфигурации
+    - find $HOME/$RXCLIENT_CONFDIR/ -mindepth 1 -mtime +$DEV_EXPIRE_IN -print -delete || echo "ignore delete old configs error"
+    - |
+      echo "                 SERVER IP: $RX_SERVER_IP"
+      echo "           RXCLIENT CONFIG: rx-etersoft-$BUILD_ID"
+      echo "REMOTE CONNECT to RXSERVER: ssh -p $CI_BUILD_ID guest@$(hostname -s)"
+
+  only:
+    - /^c7-docker-ci-.*/
+
+  tags:
+    - rx-test-builder
+
+Cleanup:
+  stage: cleanup
+  when: manual
+  before_script:
+    - export DAAS_TEMPLATES_DIR="$HOME/.daas/templates"
+    - export DAAS_ADDONS_DIR="$HOME/.daas/addons"
+    - export DAAS_OUTDIR="$CI_PROJECT_DIR/rx-etersoft"
+    - export "SERVICE_NAME=rx-etersoft-$BUILD_ID"
+  script:
+    - echo "Stop & remove containers"
+    - daas gen
+    - cd $DAAS_OUTDIR/rx-etersoft-$BUILD_ID/
+    - docker-compose down
+    #- docker image prune -f
+    #- docker container prune -f
+    #- docker volume prune -f
+  tags:
+    - rx-test-builder
+  only:
+    - /^c7-docker-ci-.*/
+
+Stop all rx containers:
+  stage: cleanup
+  when: manual
+  script:
+    - export RX_CLIST=$(docker ps | grep rx-etersoft | grep build | awk '{print $1}')
+    - test -n "$RX_CLIST" && docker stop $RX_CLIST
+    - test -n "$RX_CLIST" && docker rm $RX_CLIST
+  tags:
+    - rx-test-builder
+  only:
+    - /^c7-docker-ci-.*/
