(CI): added event to telegram for changes in 'c7' branch

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -44,6 +44,21 @@ Release:
   tags:
     - rx-build
 
+Event to telegram:
+  stage: build
+  when: always
+  script:
+    - |
+      echo "release (c7):" > last_changes.txt
+      echo "-------------" >> last_changes.txt
+      echo "" >> last_changes.txt
+      rpmlog -q --last-changelog >> last_changes.txt
+      rx_bot_pub_file.py last_changes.txt || echo "ignore event bot error.."
+  only:
+    - c7
+  tags:
+    - rx-build
+
 test build:
   stage: build
   script:
