Add parametr ENABLE_CUPS_DIALOG for disable

diff --git a/freenx-server/nxdialog b/freenx-server/nxdialog
--- a/freenx-server/nxdialog
+++ b/freenx-server/nxdialog
@@ -471,11 +471,16 @@ helper_dialog_printer()
 	# Do we have old printer information present?
 	if [ -n "$PRINTER_INFORMATION" ]
 	then
-		DIALOG_MESSAGE=$(echo -e "Found driver for printer $DIALOG_PRINTER.\n\nOld choice was: ${PRINTER_INFORMATION[3]}.\n\nIf you want to keep the settings click on 'Ok' \n- else click on 'Configure'.") ${dialog_interface}_printer_ask
-		RC=$?
-		# bail out with exit code 2 in case the user cancelled the operation
-		[ $RC -eq 2 ] && echo "cancel: aborted" && exit 2
-		[ $RC -eq 0 ] && PRINTER_CONFIGURE="no"
+		if [ "$ENABLE_CUPS_DIALOG" = "1" ]
+		then
+			DIALOG_MESSAGE=$(echo -e "Found driver for printer $DIALOG_PRINTER.\n\nOld choice was: ${PRINTER_INFORMATION[3]}.\n\nIf you want to keep the settings click on 'Ok' \n- else click on 'Configure'.") ${dialog_interface}_printer_ask
+			RC=$?
+			# bail out with exit code 2 in case the user cancelled the operation
+			[ $RC -eq 2 ] && echo "cancel: aborted" && exit 2
+			[ $RC -eq 0 ] && PRINTER_CONFIGURE="no"
+		else
+			PRINTER_CONFIGURE="no"
+		fi
 	fi
 	
 	VENDOR=""
