rxsetup: add docmd for illustrate commands

diff --git a/freenx-server/rxsetup b/freenx-server/rxsetup
--- a/freenx-server/rxsetup
+++ b/freenx-server/rxsetup
@@ -1,20 +1,46 @@
 #!/bin/bash
-# Etersoft, 2010
+# Etersoft, 2010, 2012
 # 2010 (c) Devaev Maxim, <mdevaev@etersoft.ru>
 # 2010 (c) Baranov Denis, <baraka@etersoft.ru>
+# 2012 (c) Vitaly Lipatov, <lav@etersoft.ru>
 #
-# rxsetup - script for fast configuration of NX
+# rxsetup - script for fast configuration of RX@Etersoft
 #
 #####
 
+# Print command line and run command line
+showcmd()
+{
+	if [ -z "$quiet" ] ; then
+		#set_boldcolor $GREEN
+		local PROMTSIG="\$"
+		[ "$UID" = 0 ] && PROMTSIG="#"
+		echo " $PROMTSIG $@"
+		#restore_color
+	fi >&2
+}
+
+# Print command line and run command line
+docmd()
+{
+	showcmd "$@"
+	"$@"
+}
+
+
 unlock_nx_user()
 {
-        passwd -u nx
+        docmd passwd -u nx
 }
 
 do_chkconfig_on()
 {
-        chkconfig $1 on 2>/dev/null || update-rc.d $1 defaults
+        CHKCONFIG=$(which chkconfig 2>/dev/null)
+        if [ -n "$CHKCONFIG" ] ; then
+            docmd $CHKCONFIG $1 on
+        else
+            docmd update-rc.d $1 defaults
+        fi
 }
 
 
@@ -23,24 +49,26 @@ start_sshd()
         # FIXME Lav: нужно воспользоваться distr_vendor для определения системы
         for sshd in ssh sshd openssh opensshd; do
                 if [ -e /etc/init.d/$sshd ]; then
-                        /etc/init.d/$sshd start
+                        docmd /etc/init.d/$sshd start
                         RETVAL="$?"
                         do_chkconfig_on $sshd
+                        return "$RETVAL"
                 fi
         done
-
+        echo "FIXME: cannot find ssh service name, TODO for systemd?"
+        RETVAL=1
         return "$RETVAL"
 }
 
 enable_cupsd()
 {
-        chmod 755 /usr/sbin/cupsd && \
-        chmod 711 /usr/lib/cups/backend/ipp
+        docmd chmod 755 /usr/sbin/cupsd || return
+        docmd chmod 711 /usr/lib/cups/backend/ipp || return
 }
 
 nx_install()
 {
-        nxsetup --setup-nomachine-key --install
+        docmd nxsetup --setup-nomachine-key --install
 }
 
 start_freenx_server()
@@ -54,12 +82,12 @@ start_freenx_server()
 check_expect()
 {
 	EXPECT=`which expect 2>/dev/null`
-	[ -n "$EXPECT" ] || echo "Error: please install expect"
+	[ -n "$EXPECT" ] || echo "Error: please install expect package"
 }
 
 clean_freenx()
 {
-	rm -fr /var/lib/nxserver/home/.ssh/known_hosts
+	docmd rm -fr /var/lib/nxserver/home/.ssh/known_hosts
 }
 
 rxsetup_stages()
